# Generated by Django 3.1.3 on 2020-11-19 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique_for_date='date')),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='events_images')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('allowed_attendees', models.IntegerField()),
                ('waitlist', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('attendees', models.ManyToManyField(blank=True, default=None, related_name='atendees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
                'unique_together': {('title', 'date')},
            },
        ),
    ]
